import { randomUUID } from 'node:crypto'
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest'
import { ObjectId, type Db, type Document, type MongoClient } from 'mongodb'
import { NextRequest } from 'next/server'
import { getClientPromise } from './mongodb'
import * as mongo from './mongodb'
import { createCragWithCreatorPermission } from './crag-creation'
import { createCragPermission, createRoute, deleteCragPermission, getCragPermission, getRouteById, updateRoute } from './db'
import { createFaceManagement, type FaceObjectStore } from './face-management'
import { createBetaHandlers } from './beta-api'

// Do not read application .env files or accept the application's Mongo URI.
// This suite needs an explicit local test URI and creates every database itself.
vi.mock('./logger', () => ({ createModuleLogger: () => ({ info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() }) }))

let client: MongoClient | undefined
let db: Db
let databaseName = ''
const ownedDatabases = new Set<string>()
const cragInput = { id: 'test-crag', name: 'Test crag', cityId: 'fixture-city', location: 'Fixture', description: 'Fixture', approach: 'Fixture' }
const userId = 'abcdef1234567890abcdef12'
const grantInput = { userId, cragId: cragInput.id, role: 'manager' as const, assignedBy: 'fixture-admin' }
const line = [{ x: 0.1, y: 0.2 }, { x: 0.8, y: 0.9 }]
const changedLine = [{ x: 0.2, y: 0.3 }, { x: 0.7, y: 0.8 }]
const face = { cragId: cragInput.id, area: 'B', faceId: 'wall' }
const annotation = { area: 'B', faceId: 'wall', topoLine: line }

function requireTestUri(): string {
  const uri = process.env.BLOCTOP_TEST_MONGODB_URI
  if (!uri) throw new Error('Set BLOCTOP_TEST_MONGODB_URI explicitly; application Mongo configuration is never used')
  const parsed = new URL(uri)
  if (parsed.protocol !== 'mongodb:' || !['127.0.0.1', 'localhost', '[::1]'].includes(parsed.hostname)
      || parsed.searchParams.get('replicaSet') !== 'bloctop-test') {
    throw new Error('Integration tests require a loopback Mongo URI with replicaSet=bloctop-test')
  }
  return uri
}

async function dropOwnedDatabase(name: string) {
  if (!client || !ownedDatabases.has(name) || !/^bloctop_test_[a-f0-9]{32}$/.test(name)) {
    throw new Error('Refusing to delete a database not generated by this test process')
  }
  await client.db(name).dropDatabase()
  ownedDatabases.delete(name)
}

beforeAll(async () => {
  process.env.MONGODB_URI = requireTestUri()
  client = await getClientPromise()
  const hello = await client.db('admin').command({ hello: 1 })
  expect(hello.setName).toBe('bloctop-test')
  expect(hello.isWritablePrimary).toBe(true)
})

beforeEach(async () => {
  if (!client) throw new Error('Test Mongo client was not established')
  databaseName = `bloctop_test_${randomUUID().replaceAll('-', '')}`
  ownedDatabases.add(databaseName)
  process.env.MONGODB_DB_NAME = databaseName
  db = client.db(databaseName)
})

afterEach(async () => {
  vi.restoreAllMocks()
  if (ownedDatabases.has(databaseName)) await dropOwnedDatabase(databaseName)
})

afterAll(async () => {
  try {
    for (const name of [...ownedDatabases]) await dropOwnedDatabase(name)
  } finally {
    await client?.close()
  }
})

async function prepareCragCollections() {
  await db.createCollection('crags')
  await db.createCollection('crag_permissions')
}

async function prepareRoute(overrides: Document = {}) {
  await db.collection('crags').insertOne({ _id: cragInput.id as unknown as ObjectId })
  await db.collection<Document>('routes').insertOne({ _id: 42 as unknown as ObjectId,
    cragId: cragInput.id, name: 'Route', grade: 'V1', area: 'A',
    faceId: 'wall', faceArea: 'B', topoLine: line, topoAnnotations: [annotation], ...overrides })
  const objects = new Map([['test-crag/B/wall.jpg', { etag: 'fixture-etag', contentType: 'image/jpeg' }]])
  const store: FaceObjectStore = {
    head: async key => objects.get(key) ?? null,
    list: async () => ({ keys: [...objects.keys()] }),
    copy: async (source, target) => { objects.set(target, { ...objects.get(source)!, etag: 'copied' }) },
    put: async () => {}, delete: async key => { objects.delete(key) },
  }
  return createFaceManagement({ getDatabase: async () => db, getObjectStore: () => store })
}

/** Coordinate two real Mongo writers without changing either command or result. */
function interleaveNextRouteWrite(operation: () => Promise<unknown>) {
  let pending = true
  const realRoutes = db.collection('routes')
  const routes = new Proxy(realRoutes, { get(target, property) {
    if (property === 'findOneAndUpdate') return async (...args: unknown[]) => {
      if (pending) { pending = false; await operation() }
      return Reflect.apply(target.findOneAndUpdate, target, args)
    }
    const value = Reflect.get(target, property)
    return typeof value === 'function' ? value.bind(target) : value
  } })
  const coordinatedDb = new Proxy(db, { get(target, property) {
    if (property === 'collection') return (name: string) => name === 'routes' ? routes : target.collection(name)
    const value = Reflect.get(target, property)
    return typeof value === 'function' ? value.bind(target) : value
  } })
  vi.spyOn(mongo, 'getDatabase').mockResolvedValue(coordinatedDb)
}

describe('real isolated Mongo transaction and concurrency acceptance', () => {
  it('rolls back the crag insert when a collection validator rejects the creator grant', async () => {
    await db.createCollection('crags')
    await db.createCollection('crag_permissions', { validator: { assignedBy: { $ne: 'rejected-creator' } }, validationAction: 'error' })
    await expect(createCragWithCreatorPermission(cragInput, 'rejected-creator')).rejects.toMatchObject({ code: 121 })
    expect(await db.collection('crags').countDocuments()).toBe(0)
    expect(await db.collection('crag_permissions').countDocuments()).toBe(0)
  })

  it('recovers an identical post-commit retry without replacing stored content', async () => {
    await prepareCragCollections()
    const created = await createCragWithCreatorPermission(cragInput, userId)
    await db.collection('crags').updateOne({ _id: cragInput.id as unknown as ObjectId }, { $set: { mediaRevision: 'fixture-media', areas: ['B'] } })
    const replay = await createCragWithCreatorPermission(cragInput, userId)
    expect(created.replayed).toBe(false)
    expect(replay).toMatchObject({ replayed: true, crag: { mediaRevision: 'fixture-media', areas: ['B'] } })
    expect(await db.collection('crags').countDocuments()).toBe(1)
    expect(await db.collection('crag_permissions').countDocuments()).toBe(1)
  })

  it('concurrent identical crag creation produces one crag and one creator grant', async () => {
    await prepareCragCollections()
    const results = await Promise.all(Array.from({ length: 8 }, () => createCragWithCreatorPermission(cragInput, userId)))
    expect(results.filter(result => !result.replayed)).toHaveLength(1)
    expect(await db.collection('crags').countDocuments()).toBe(1)
    expect(await db.collection('crag_permissions').countDocuments()).toBe(1)
  })

  it('competing creators never overwrite the winner or acquire its grant', async () => {
    await prepareCragCollections()
    const creators = [userId, '1234567890abcdef12345678']
    const results = await Promise.allSettled(creators.map(creator => createCragWithCreatorPermission(cragInput, creator)))
    expect(results.filter(result => result.status === 'fulfilled')).toHaveLength(1)
    expect(results.filter(result => result.status === 'rejected')).toMatchObject([{ reason: { code: 'CRAG_ID_CONFLICT' } }])
    const stored = await db.collection('crags').findOne({ _id: cragInput.id as unknown as ObjectId })
    expect(await db.collection('crag_permissions').countDocuments()).toBe(1)
    expect(await db.collection('crag_permissions').findOne({ userId: stored?.createdBy })).not.toBeNull()
  })

  it('16 equivalent grant upserts succeed once using only the built-in _id unique index', async () => {
    await db.createCollection('crag_permissions')
    expect((await db.collection('crag_permissions').indexes()).map(index => index.name)).toEqual(['_id_'])
    const results = await Promise.allSettled(Array.from({ length: 16 }, (_, i) => createCragPermission({ ...grantInput, userId: i % 2 ? userId.toUpperCase() : userId })))
    expect(results.filter(result => result.status === 'fulfilled')).toHaveLength(1)
    expect(results.filter(result => result.status === 'rejected')).toHaveLength(15)
    for (const result of results) if (result.status === 'rejected') expect(result.reason).toMatchObject({ code: 11000 })
    expect(await db.collection('crag_permissions').countDocuments()).toBe(1)
  })

  it('matches legacy mixed-case ObjectId grants and revokes all duplicates without affecting another crag', async () => {
    await db.collection('crag_permissions').insertMany([
      { ...grantInput, userId: 'AbCdEf1234567890aBcDeF12', createdAt: new Date() },
      { ...grantInput, userId: userId.toUpperCase(), createdAt: new Date() },
      { ...grantInput, cragId: 'another-crag', createdAt: new Date() },
    ])
    expect(await getCragPermission(userId, cragInput.id)).not.toBeNull()
    await expect(createCragPermission(grantInput)).rejects.toMatchObject({ code: 11000 })
    expect(await deleteCragPermission(userId, cragInput.id)).toBe(true)
    expect(await db.collection('crag_permissions').countDocuments({ cragId: cragInput.id })).toBe(0)
    expect(await db.collection('crag_permissions').countDocuments()).toBe(1)
  })

  it('allocates unique route IDs during concurrent first-time initialization and never reuses a deleted maximum', async () => {
    await db.collection<Document>('routes').insertOne({ _id: 100 as unknown as ObjectId })
    const routes = await Promise.all(Array.from({ length: 32 }, () => createRoute({ name: 'Fixture', grade: 'V1', area: 'A', cragId: cragInput.id })))
    expect(routes.map(route => route.id).sort((a, b) => a - b)).toEqual(Array.from({ length: 32 }, (_, i) => 101 + i))
    expect(routes.every(route => route.topoVersion === 0)).toBe(true)
    await db.collection<Document>('routes').deleteOne({ _id: 132 as unknown as ObjectId })
    expect((await createRoute({ name: 'Next fixture', grade: 'V1', area: 'A', cragId: cragInput.id })).id).toBe(133)
  })

  it.each(['rename', 'delete'] as const)('rejects an old Topo draft after face %s using the real Mongo filter', async operation => {
    const management = await prepareRoute()
    if (operation === 'rename') await management.rename(face, 'new-wall')
    else await management.remove(face)
    const committed = await getRouteById(42)
    expect(committed?.topoVersion).toBe(1)
    await expect(updateRoute(42, { topoAnnotations: [annotation] }, { expectedTopoVersion: 0 })).rejects.toMatchObject({ status: 409, route: { topoVersion: 1 } })
    await expect(updateRoute(42, { topoAnnotations: [annotation] })).rejects.toMatchObject({ status: 428 })
    expect(await getRouteById(42)).toEqual(committed)
  })

  it('a real face deletion between route snapshot and CAS defeats the stale conditional write', async () => {
    const management = await prepareRoute()
    interleaveNextRouteWrite(() => management.remove(face))
    await expect(updateRoute(42, { topoAnnotations: [{ ...annotation, topoLine: changedLine }] }, { expectedTopoVersion: 0 }))
      .rejects.toMatchObject({ status: 409, route: { topoVersion: 1, topoAnnotations: [] } })
    expect(await getRouteById(42)).toMatchObject({ topoVersion: 1, topoAnnotations: [] })
    expect(await getRouteById(42)).not.toHaveProperty('faceId')
  })

  it('legacy area metadata retries a concurrent real rename without restoring its old identity or incrementing again', async () => {
    const management = await prepareRoute({ area: 'B' })
    await db.collection<Document>('routes').updateOne({ _id: 42 as unknown as ObjectId }, { $unset: { faceArea: '', topoAnnotations: '' } })
    interleaveNextRouteWrite(() => management.rename(face, 'new-wall'))
    expect(await updateRoute(42, { area: 'C' })).toMatchObject({ area: 'C', faceArea: 'B', faceId: 'new-wall', topoVersion: 1 })
    expect((await getRouteById(42))?.topoVersion).toBe(1)
  })

  it('concurrent draft saves allow one winner while a real Beta submission survives and does not increment Topo', async () => {
    await prepareRoute()
    const beta = createBetaHandlers({ getDatabase: async () => db,
      requireAuth: async () => ({ userId: 'fixture-submitter', role: 'user' }), canEditCrag: async () => true })
    const results = await Promise.allSettled([
      updateRoute(42, { topoAnnotations: [{ ...annotation, topoLine: changedLine }] }, { expectedTopoVersion: 0 }),
      updateRoute(42, { topoAnnotations: [{ ...annotation, topoTension: 0.8 }] }, { expectedTopoVersion: 0 }),
      beta.POST(new NextRequest('http://localhost/api/beta', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-forwarded-for': '127.0.0.9' },
        body: JSON.stringify({ routeId: 42, url: 'https://www.xiaohongshu.com/explore/69888b980000000015021e7b' }) })),
    ])
    expect(results.slice(0, 2).filter(result => result.status === 'fulfilled')).toHaveLength(1)
    expect(results.slice(0, 2).filter(result => result.status === 'rejected')).toMatchObject([{ reason: { status: 409 } }])
    expect(results[2].status).toBe('fulfilled')
    if (results[2].status === 'fulfilled') expect((results[2].value as Response).status).toBe(201)
    const stored = await getRouteById(42)
    expect(stored?.topoVersion).toBe(1)
    expect(stored?.betaLinks).toHaveLength(1)
    expect(stored?.betaLinks?.[0].noteId).toBe('69888b980000000015021e7b')
  })
})
